### PR TITLE
Type object already exists. Issue #110

### PR DESCRIPTION
**Pull request by fabricek**
When doing "php app / console cache: clear" error [Doctrine\ODM\MongoDB\Mapping\MappingException]

### CODE REVIEW

**Comment by iampersistent** [comment]
I want to look into this further, so if you can adjust the code based on my comment, I'll merge this, but leave #110 open.

**Comment by fabricek** [comment]
ok i do this now.

**Comment by fabricek** [comment]
Done thanks for point it out.

2014-04-14 8:27 GMT+02:00 Richard Shank notifications@github.com:

> I want to look into this further, so if you can adjust the code based on
> my comment, I'll merge this, but leave #110https://github.com/vespolina/vespolina-sandbox/issues/110open.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/vespolina/vespolina-sandbox/pull/114#issuecomment-40336391
> .

## 

Cordialement,

Fabrice Kuissu

**Comment by iampersistent** [comment]
Awesome! Thanks!

**Pull request merged**
